# Generated by Django 4.2.4 on 2023-08-22 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employé',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prénom', models.CharField(blank=True, max_length=30)),
                ('Nom', models.CharField(blank=True, max_length=30)),
                ('Date_Naissance', models.DateField(blank=True, null=True)),
                ('Lieu_Naissance', models.CharField(blank=True, max_length=40, null=True)),
                ('Adresse', models.CharField(blank=True, max_length=60, null=True)),
                ('Echelon', models.SmallIntegerField(blank=True, null=True)),
                ('Categorie', models.SmallIntegerField(blank=True, null=True)),
                ('Salaire_de_Base', models.DecimalField(blank=True, decimal_places=3, max_digits=8)),
                ('CIN', models.CharField(blank=True, max_length=8)),
                ('Id_Banque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.banque')),
            ],
        ),
        migrations.CreateModel(
            name='Etat_Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='employé',
            name='Id_Etat_Contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.etat_contrat'),
        ),
        migrations.AddField(
            model_name='employé',
            name='Id_Local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.local'),
        ),
        migrations.AddField(
            model_name='employé',
            name='Id_Poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.poste'),
        ),
    ]
