# Generated by Django 4.2.4 on 2023-08-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_banque_employé_etat_contrat_local_poste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Affectation', models.DateField(blank=True, null=True)),
                ('Numero', models.CharField(max_length=40)),
                ('Type', models.CharField(choices=[('CNSS', 'CNSS'), ('SVIP', 'SVIP')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10)),
                ('sit_conjug', models.CharField(choices=[('M', 'Marié'), ('C', 'Célibataire'), ('D', 'Divorcé'), ('V', 'Veufe')], max_length=40)),
                ('nb_Enfants', models.SmallIntegerField(blank=True, null=True)),
                ('chef_famille', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employé',
            name='Id_Banque',
        ),
        migrations.RemoveField(
            model_name='employé',
            name='Id_Etat_Contrat',
        ),
        migrations.AddField(
            model_name='banque',
            name='Paiement',
            field=models.CharField(choices=[('C', 'Chèque'), ('V', 'Virement'), ('E', 'Espèce')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='banque',
            name='RIB',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employé',
            name='Id_Local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.banque'),
        ),
        migrations.AlterField(
            model_name='etat_contrat',
            name='Designation',
            field=models.CharField(choices=[('S', 'SIVP'), ('C', 'Contractuel'), ('O', 'Occasionnel'), ('P', 'Permanent'), ('T', 'Titulaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='local',
            name='Designation',
            field=models.CharField(choices=[('S', 'Siège'), ('M1', 'Marsa corniche'), ('M2', 'Marsa saada'), ('TS', 'Tunis city'), ('AS', 'Azur city'), ('MS', 'Mall of Sousse'), ('MT', 'Mall de Tunis')], max_length=25),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Etat_Contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.etat_contrat')),
                ('Id_Local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.local')),
                ('Id_Poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.poste')),
            ],
        ),
        migrations.AddField(
            model_name='employé',
            name='Id_Affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.affectation'),
        ),
        migrations.AddField(
            model_name='employé',
            name='Id_CNSS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.cnss'),
        ),
        migrations.AlterField(
            model_name='employé',
            name='Id_Poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.situation'),
        ),
    ]
