# Generated by Django 4.2.4 on 2023-08-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_cnss_situation_remove_employé_id_banque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employé',
            old_name='Id_Local',
            new_name='Id_Banque',
        ),
        migrations.RenameField(
            model_name='employé',
            old_name='Id_Poste',
            new_name='Id_Situation',
        ),
    ]
