# Generated by Django 4.2.4 on 2023-08-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_rename_id_local_employé_id_banque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banque',
            name='RIB',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
