# Generated by Django 4.2.4 on 2023-08-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_alter_banque_rib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnss',
            name='Numero',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='employé',
            name='CIN',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
