# Generated by Django 4.2.4 on 2023-08-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_employé_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employé',
            name='Télephone',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
