# Generated by Django 4.2.4 on 2023-08-26 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_banque_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congés',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Congés_Annuels', models.SmallIntegerField(blank=True, default=26)),
                ('Congés_Maladie', models.SmallIntegerField(blank=True, default=7)),
                ('Congés_Sans_Solde', models.SmallIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='employé',
            name='Id_Congés',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.congés'),
        ),
    ]
