# Generated by Django 4.2.4 on 2023-09-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_alter_employé_id_banque_alter_employé_id_cnss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='congés',
            name='Absence',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
